### ISSUE TITLE
c_src/sqlite3_drv.c: warning: too many arguments for format [-Wformat-extra-args]

### ISSUE THREAD

**Issue by debalance** [processone/erlang-sqlite3#1]
Hi,

for some reason I don't know, erlang-sqlite3 doesn't build on debian sid (a.k.a. unstable) anymore.
The Error is located in the C code.

Could be related to erlang 19.1.1 or gcc 6.2.0 or something completely different.

The complete build log is available here:
https://bugs.debian.org/839351

**Comment by debalance** [comment]
As it turned out the build failure was caused by a bug in rebar (https://bugs.debian.org/840431).

It would be nice nevertheless to get these warnings fixed:

> Compiling c_src/sqlite3_drv.c
> c_src/sqlite3_drv.c: In function 'exec_async_command':
> c_src/sqlite3_drv.c:22:25: warning: too many arguments for format [-Wformat-extra-args]
>        fprintf(drv->log, "[ERROR](%s:%d) " M "\n", **FILE**, **LINE**, **VA_ARGS**); \
>                          ^
> c_src/sqlite3_drv.c:459:7: note: in expansion of macro 'LOG_ERROR'
>        LOG_ERROR("driver_async call failed", 0);
>        ^~~~~~~~~
> c_src/sqlite3_drv.c:24:23: warning: too many arguments for format [-Wformat-extra-args]
>        fprintf(stderr, "[ERROR](%s:%d) " M "\n", **FILE**, **LINE**, **VA_ARGS**); \
>                        ^
> c_src/sqlite3_drv.c:459:7: note: in expansion of macro 'LOG_ERROR'
>        LOG_ERROR("driver_async call failed", 0);
>        ^~~~~~~~~

**Comment by Neustradamus** [comment]
@debalance: Several years after, the problem is always here?

**Comment by badlop** [comment]
> As it turned out the build failure was caused by a bug in rebar (https://bugs.debian.org/840431).

Right. In fact, compiling erlang-sqlite3 (and any other library) when path contains ~ using rebar2, crashes even when using the most recent from https://github.com/rebar/rebar

On the other hand, compiling with rebar3 is now fully supported, so probably it's time to use rebar3 by default.

> It would be nice nevertheless to get these warnings fixed:

Umm, I don't get those warnings now, neither using rebar2 or rebar3. Maybe it was solved in https://github.com/processone/erlang-sqlite3/commit/b054133c87ec141b42302d777063063f101f57cb ?
