### ISSUE TITLE
Using sqlite3 from gen_server

### ISSUE THREAD

**Issue by lightuponcloud** [processone/erlang-sqlite3#10]
Hello

I'm using this code:
`{ok, Pid0} = sqlite3:open(DbName, [{file, TempFn1}])`

Sometimes I receive errors like the following.
```
2023-02-21 20:35:10 =CRASH REPORT====
  crasher:
    initial call: sqlite_server:init/1
    pid: <0.866.0>
    registered_name: sqlite_server
    exception error: {{badmatch,{error,{already_started,<0.25418.0>}}},[{sqlite_server,open_db,4,[{file,"src/sqlite_se
rver.erl"},{line,324}]},{sqlite_server,handle_cast,2,[{file,"src/sqlite_server.erl"},{line,211}]},{gen_server,try_disp
atch,4,[{file,"gen_server.erl"},{line,689}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,765}]},{proc_lib,
init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
    ancestors: [<0.842.0>]
    message_queue_len: 0
    messages: []
    links: [<0.25418.0>,<0.842.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 28
    reductions: 481871
  neighbours:
    neighbour: [{pid,<0.25418.0>},{registered_name,db_files},{initial_call,{sqlite3,init,['Argument__1']}},{current_fu
nction,{gen_server,loop,7}},{ancestors,[sqlite_server,<0.842.0>]},{message_queue_len,0},{links,[<0.866.0>,#Port<0.1391
9>]},{trap_exit,false},{status,waiting},{heap_size,376},{stack_size,12},{reductions,153},{current_stacktrace,[{gen_ser
ver,loop,7,[{file,"gen_server.erl"},{line,437}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}]
```

As I can see, the reason is in this line in sqlite3:open/2
`        true -> gen_server:start_link({local, DbName}, ?MODULE, Opts, [])
`

It starts a named process and since previous registered process exists with that name, it fails.
Docstring for that function says:

```
If the name is an atom other than 'anonymous', it's used for registering the gen_server and must be unique.
```
I think that approach is prone to errors.

**Comment by prefiks** [comment]
I don't see anything wrong with that, you want named table that you can access by just name you can have only one (and you code can absolutely handle that already_started error, and work as table was normally opened), how we could know which table should be used with given name if we created separated table on each call? If you don't care about table name use anonymous.

**Comment by lightuponcloud** [comment]
The problem here is that gen_server:start_link is hidden behind open().
It would be more logical to allow user to start process instead and then call sqlite3:open/2.

also I do not find unregister call. Those named processes are left in memory until process restarts ?

**Comment by prefiks** [comment]
Name is registered until process is run, you can terminate it by calling sqlte3:close
