### ISSUE TITLE
rebar included in repo do not work with new Erlang

### ISSUE THREAD

**Issue by lightuponcloud** [processone/erlang-sqlite3#9]
When you run rebar it raises error:

deps/sqlite3$ ./rebar
escript: exception error: undefined function rebar:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3

Erlang 25

**Comment by prefiks** [comment]
Yes R25 in incompatible with .beam files generated by older version, i will remove it. It's better to use system one.

**Comment by prefiks** [comment]
Fixed by 9e93d0c265bff73dd3510ec6b1b5a7d083ba9136
